openapi: 3.0.0
info:
  title: Virtual Mattress
  description: Library Service.
  version: 1.0.0
tags:
  - name: "Finance"
paths:
  /expenses/{accountId}:
    get:
      summary: These are all the expenses
      operationId: getAllExpensesByAccount
      parameters:
        - $ref: '#/components/parameters/accountIdParam'
      responses:
        "200":
          description: Get all the expenses for one account
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Expense'
  /expense:
    post:
      summary: Add an expanse
      operationId: addExpense
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Expense'
      responses:
        "201":
          description: Expense added succesfully
          content:
            application/json:
              schema:
                allOf:
                 - $ref: '#/components/schemas/Expense'

components:
  schemas:
    Expense:
      title: Expense
      type: object
      properties:
        title:
          description: Expense title
          type: string
          example: "Lunch"
        label:
          description: Label of the expense
          type: array
          items:
            type: string
            example: ["Food", "Birthday"]
        value:
          description: Value of the expense
          type: number
          example: 15
        currency:
          description: Currency of the expense
          type: string
          example: "€"
        dateTime:
          description: Time and hour of the expanse
          type: string
          format: date
          example: "30-03-2021:00:18"
        account:
          description: account associated with the expanse
          type: number
          format: float
          example: 1
  parameters:
    accountIdParam:
      in: path
      name: accountId
      required: true
      schema:
        type: number
        example: 12345
